### ISSUE TITLE
Consider declaring format_glendon as a dependency

### ISSUE THREAD

**Issue by mudrd8mz** [patrickthibaudeau/moodle-atto_etitle#1]
The plugin itself seems to work. But without the Glendon course format, it may be pretty confusing as the "Tab" option produces a plain H2 heading. 

I am wondering, would it make sense to declare a dependency on the format_glendon, even if technically, this plugin does not need that one?

**Comment by patrickthibaudeau** [comment]
Hi David,

Makes sense. I made the modification.

Thank you
